---
output:
  pdf_document: default
urlcolor: blue
header-includes:    
  - \usepackage{lastpage}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhead[CO, CE]{Ilke Sun, 1004133109}
  - \fancyfoot[CO, CE]{\thepage \ of \pageref{LastPage}}
---
```{r setup, message = FALSE, echo=FALSE}
# Students: You probably shouldn't change any of the code in this chunk.

# These are the packages you will need for this activity
packages_needed <- c("tidyverse", "googledrive", "readxl", "janitor", 
                     "lubridate", "opendatatoronto", "ggthemes")

package.check <- lapply(
  packages_needed,
  FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE)
    }
  }
)

# Credit: package.check based on a helpful post from Vikram Baliga https://vbaliga.github.io/verify-that-r-packages-are-installed-and-loaded/

# Load tidyverse
library(tidyverse)
library(readxl)
library(janitor)
library(opendatatoronto)
library(ggthemes)

# Set so that long lines in R will be wrapped:
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80), echo = FALSE)
```


```{r getdata, eval = FALSE, echo=FALSE}
# Students: You probably shouldn't change any of the code in this chunk BUT...

# This chunk loads the most recent data from Toronto City and the data from OpenToronto.

# You have to RUN this chunk by hand to update the data as 
#   eval is set to FALSE to limit unnecessary requsts on the site.

###################################################
# Step one: Get the COVID data from Toronto City. #
###################################################

googledrive::drive_deauth()

#url1 <- "https://drive.google.com/file/d/11KF1DuN5tntugNc10ogQDzFnW05ruzLH/view"
#googledrive::drive_download(url1, path="data/CityofToronto_COVID-19_Daily_Public_Reporting.xlsx", overwrite = TRUE)

url2 <- "https://drive.google.com/file/d/1jzH64LvFQ-UsDibXO0MOtvjbL2CvnV3N/view"
googledrive::drive_download(url2, path = "data/CityofToronto_COVID-19_NeighbourhoodData.xlsx", overwrite = TRUE)

# this removes the url object that we don't need anymore
rm(url1, url2)

#####################################################################
# Step two: Get the data neighbourhood data from Open Data Toronto. #
#####################################################################

nbhoods_shape_raw <- list_package_resources("neighbourhoods") %>% 
  get_resource()

saveRDS(nbhoods_shape_raw, "data/neighbourhood_shapefile.Rds")

nbhood_profile <- search_packages("Neighbourhood Profile") %>%
  list_package_resources() %>% 
  filter(name == "neighbourhood-profiles-2016-csv") %>% 
  get_resource()

saveRDS(nbhood_profile, "data/neighbourhood_profile.Rds")
```


```{r load_data, echo=FALSE}
######################################################
# Step three: Load the COVID data from Toronto City. #
######################################################

# Saving the name of the file as an object and then using the object name in the
# following code is a helpful practice. Why? If we change the name of the file 
# being used, we'll only have to change it in one place. This helps us avoid 
# 'human error'.

daily_data <- "data/CityofToronto_COVID-19_Daily_Public_Reporting.xlsx"

# Cases reported by date
reported_raw <- read_excel(daily_data, sheet = 5) %>% 
  clean_names()

# Cases by outbreak type
outbreak_raw <- read_excel(daily_data, sheet = 3) %>% 
  clean_names()

# When was this data updated?
date_daily <- read_excel(daily_data, sheet = 1) %>% 
  clean_names()

# By neighbourhood
neighbourood_data <- "data/CityofToronto_COVID-19_NeighbourhoodData.xlsx"

# Cases reported by date
nbhood_raw <- read_excel(neighbourood_data, sheet = 2) %>% 
  clean_names()

# Date the neighbourhood data was last updated
date_nbhood <- read_excel(neighbourood_data, sheet = 1) %>% 
  clean_names()

#don't need these anymore
rm(daily_data, neighbourood_data)

#############################################################
# Step four: Load the neighbourhood data from Toronto City. #
#############################################################

# Get neighbourhood profile data
nbhood_profile <- readRDS("data/neighbourhood_profile.Rds")

# Get shape data for mapping 
nbhoods_shape_raw <- readRDS("data/neighbourhood_shapefile.Rds") %>% 
  sf::st_as_sf() ## Makes sure shape info is in the most up to date format
```

Code last run `r Sys.Date()`.  
Daily: `r date_daily[1,1]`.   
Neighbourhood: `r date_nbhood[1,1]`. 

# Task 1: Daily cases
## Data wrangling

```{r cases_dw, echo = T}
reported <- reported_raw %>% 
  mutate(reported_date = date(reported_date)) %>% 
  rename("Date" = "reported_date",
         "Recovered" = "recovered",
         "Active" = "active",
         "Deceased" = "deceased") %>% 
  select(Date, Recovered, Deceased, Active) %>% 
  complete(Date = seq.Date(min(Date), max(Date), by = "day")) %>% 
  mutate_if(is.numeric, replace_na, replace = 0)
```

\newpage
## Data visualization

```{r cases_vis, echo = T, warning = F}
st <- date("2020-01-01")
nd <- Sys.Date()
reported %>% 
  gather("Type", "Cases", -Date) %>% 
  mutate(Type = factor(Type, levels = c("Active", "Recovered", "Deceased"))) %>% 
  ggplot(aes(x = Date, y = Cases, fill = Type)) + 
  geom_bar(position = "stack", stat = "identity") +
  theme_minimal() + 
  labs(title = "Cases reported by day in Toronto, Canada",
       subtitle = "Confirmed and probable cases",
       x = "Date",
       y = "Case count",
       caption = str_c("Created by: Ilke Sun for STA303/1002, U of T\n",
                       "Source: Ontario Ministry of Health, Integrated ", 
                       "Public Health Information System and CORES\n",
                       date_daily)) +
  theme(legend.title = element_blank(), legend.position = c(.15, .8)) +
  scale_x_date(limits = c(st, nd), date_labels = "%d %b %y") +
  scale_y_continuous(limits = c(0, 2000)) +
  scale_fill_manual("legend", values = c("Active" = "#003F5C",
                                         "Recovered" = "#86BCB6",
                                         "Deceased" = "#B9CA5D"))

rm(reported_raw, st, nd)
```

\newpage
# Task 2: Outbreak type
## Data wrangling

```{r outbreak_dw, echo = T}
st <- date(min(outbreak_raw$episode_week))
nd <- date(max(outbreak_raw$episode_week))

outbreak <- outbreak_raw %>%
  group_by(outbreak_or_sporadic) %>% 
  mutate(episode_week = date(episode_week)) %>% 
  complete(episode_week = seq.Date(st, nd, by = "week")) %>% 
  rename("OS" = "outbreak_or_sporadic") %>% 
  select(episode_week, OS, cases) %>% 
  arrange(episode_week) %>% 
  mutate(cases = replace_na(cases, replace = 0),
         OS = as.factor(OS))

levels(outbreak$OS) <- c("Outbreak associated", "Sporadic")
outbreak$OS <- factor(outbreak$OS,
                       levels = c("Sporadic", "Outbreak associated"))

outbreak_OB <- outbreak %>% 
  filter(OS == "Outbreak associated") %>% 
  mutate(total_cases = cases)
  
outbreak_OB <- outbreak_OB %>% 
  rbind(outbreak_OB) %>% 
  arrange(episode_week)

outbreak_SP <- outbreak %>% 
  filter(OS == "Sporadic") %>% 
  mutate(total_cases = cases)

outbreak_SP <- outbreak_SP %>% 
  rbind(outbreak_SP) %>% 
  arrange(episode_week)

outbreak$total_cases <- outbreak_OB$total_cases + outbreak_SP$total_cases

rm(outbreak_OB, outbreak_SP, st, nd)
```

\newpage
## Data visualization

```{r outbreak_vis, echo = T, warning = F}
st <- date("2020-01-01")
nd <- Sys.Date() + 7

outbreak %>% 
  ggplot(aes(x = episode_week, y = cases, fill = OS)) + 
  geom_bar(position = "stack", stat = "identity") +
  theme_minimal() + 
  labs(title = "Cases by outbreak type and week in Toronto, Canada",
       subtitle = "Confirmed and probable cases",
       x = "Date",
       y = "Case count",
       caption = str_c("Created by: Ilke Sun for STA303/1002, U of T\n",
                       "Source: Ontario Ministry of Health, Integrated Public ", 
                       "Health Information System and CORES\n",
                       date_daily)) +
  theme(legend.title = element_blank(), legend.position = c(.15, .8)) +
  scale_x_date(limits = date(c(st, nd)),
               date_labels = "%d %b %y") +
  scale_y_continuous(limits = c(0, max(outbreak$total_cases))) +
  scale_fill_manual("legend", values = c("Sporadic" = "#86BCB6",
                                         "Outbreak associated" = "#B9CA5D"))

rm(outbreak_raw, st, nd)
```

\newpage
# Task 3: Neighbourhoods
## Data wrangling: part 1

```{r nbhood_dw_1, echo = T}
income <- nbhood_profile %>%
  rename("id" = "_id") %>% 
  filter(Topic == "Low income in 2015") %>% 
  filter(id == 1075) %>% 
  select(-id, -Category, -Topic, -`Data Source`,
         -Characteristic, -`City of Toronto`) %>% 
  gather("neighbourhood_name", "percentage") %>% 
  mutate(percentage = as.numeric(percentage)) %>% 
  arrange(neighbourhood_name)

rm(nbhood_profile)
```

## Data wrangling: part 2

```{r nbhood_dw_2, echo = T}
nbhood_raw <- nbhood_raw %>% 
  filter(neighbourhood_name != "Missing Address/Postal Code") %>% 
  arrange(neighbourhood_name)

nbhoods_all <- nbhoods_shape_raw %>% 
  mutate(neighbourhood_name = str_remove(AREA_NAME, pattern = "\\(\\d+\\)")) %>% 
  arrange(neighbourhood_name) %>% 
  mutate(percentage = income$percentage,
         rate_per_100000 = nbhood_raw$rate_per_100_000_people)
```

## Data wrangling: part 3

```{r nbhood_dw_3, echo = T}
nbhoods_final <- nbhoods_all %>% 
  mutate(med_inc = median(percentage),
         med_rate = median(rate_per_100000)) %>% 
  mutate(nbhood_type = case_when(
    percentage >= med_inc & rate_per_100000 >= med_rate ~ 
      "Higher low income rate, higher case rate",
    percentage >= med_inc & rate_per_100000 < med_rate ~ 
      "Higher low income rate, lower case rate",
    percentage < med_inc & rate_per_100000 >= med_rate ~ 
      "Lower low income rate, higher case rate",
    percentage < med_inc & rate_per_100000 < med_rate ~ 
      "Lower low income rate, lower case rate"))

rm(nbhood_raw, nbhoods_all)
```

\newpage
## Data visualization

```{r neighbourhood_graphs_1, echo = T, fig.height=4}
nbhoods_final %>% 
  ggplot(aes(fill = percentage)) + 
  geom_sf() +
  theme_map() +
  theme(legend.position = "right") +
  labs(title = str_c("Percentage of 18 to 64 year olds living in a low income ",
                     "family (2015)"),
       subtitle = "Neighbourhoods of Toronto, Canada",
       caption = str_c("Created by: Ilke Sun for STA303/1002, U of T\n",
                       "Source: Census Profile 98-316-X2016001 ",
                       "via OpenData Toronto\n",
                       date_nbhood)) +
  scale_fill_gradient(name = "% low income",
                      low = "darkgreen",
                      high = "lightgrey")
```

\newpage

```{r neighbourhood_graphs_2, echo = T, fig.height=4}
nbhoods_final %>% 
  ggplot(aes(fill = rate_per_100000)) + 
  geom_sf() +
  theme_map() +
  theme(legend.position = "right") +
  labs(title = "COVID-19 cases per 100,000, by neighbourhood in Toronto,
       Canada",
       caption = str_c("Created by: Ilke Sun for STA303/1002, U of T\n",
                       "Source: Ontario Ministry of Health, Integrated Public ",
                       "Health Information System and CORES\n",
                       date_daily)) + 
  scale_fill_gradient(name = "Cases per 100,000",
                      low = "white",
                      high = "darkorange")
```

\newpage

```{r neighbourhood_graphs_3, echo = T, fig.height=4}
nbhoods_final %>% 
  ggplot(aes(fill = nbhood_type)) + 
  geom_sf() +
  theme_map() +
  theme(legend.position = "right") +
  labs(title ="COVID-19 cases per 100,000, by neighbourhood in Toronto, Canada",
       caption = str_c("Created by: Ilke Sun for STA303/1002, U of T\n",
                       "Income Data Source: Census Profile 98-316-X2016001",
                       "via OpenData Toronto\n",
                       "COVID Data Source: Ontario Ministry of Health,",
                       "Integrated Public\n",
                       "Health Information System and CORES\n",
                       date_daily)) +
  scale_fill_brewer(name = str_c("% of 18 to 64 year-olds in\n",
                      "low income families and\n",
                      "COVID-19 case rates"), palette = "Set1")
```




```{r, eval = FALSE}
# This chunk of code helps you prepare your assessment for submission on Crowdmark
# This is optional. If it isn't working, you can do it manually/take another approach.

# Run this chunk by hand after knitting your final version of your pdf for submission.
# A new file called 'to_submit' will appear in your working directory with each page of your assignment as a separate pdf.

# Install the required packages
if(!match("staplr", installed.packages()[,1], nomatch = FALSE))
  {install.packages("staplr")}

# Don't edit anything in this function
prep_for_crowdmark <- function(pdf=NULL){
  # Get the name of the file you're currently in. 
  this_file <- rstudioapi::getSourceEditorContext()$path
  pdf_name <- sub(".Rmd", ".pdf", sub('.*/', '', this_file))
  
  # Create a file called to_submit to put the individual files in
  # This will be in the same folder as this file is saved
  if(!match("to_submit", list.files(), nomatch = FALSE))
    {dir.create("to_submit")}
 
  # Split the files
  if(is.null(pdf)){
  staplr::split_pdf(pdf_name, output_directory = "to_submit", prefix = "page_")} else {
    staplr::split_pdf(pdf, output_directory = "to_submit", prefix = "page_") 
  }
}

prep_for_crowdmark()
```